name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  CD_Dev:
    uses: jdarguello/MELI-Challenge/.github/workflows/CD_Dev.yaml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}