name: Pipeline de Integración Continua

on:
  push:
    branches:
      - main

jobs:
  CI_quality:
    uses: jdarguello/MELI-Challenge/.github/workflows/CI_quality.yaml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}

  CI_secOps:
    uses: jdarguello/MELI-Challenge/.github/workflows/CI_secOps.yaml@main
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

  CI_artifact:
    needs: 
      - CI_quality
      - CI_secOps
    uses: jdarguello/MELI-Challenge/.github/workflows/CI_artifact.yaml@main
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

  CI_docs:
    needs: CI_artifact
    permissions:
      pages: write
      id-token: write
    uses: jdarguello/MELI-Challenge/.github/workflows/docs-deploy.yaml@main

  