name: Generación y publicación del artefacto

on:
  workflow_call:
    secrets:
        DOCKER_HUB_USERNAME:
          required: true
        DOCKER_HUB_TOKEN:
          required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/meli:${{ github.sha }} .
        working-directory: ./auth
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Push image to Docker Hub
        run: |
          docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/meli:${{ github.sha }}
        working-directory: ./auth