name: Generación y publicación del artefacto

on:
  workflow_call:
    secrets:
        DOCKER_HUB_USERNAME:
          required: true
        DOCKER_HUB_TOKEN:
          required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        working-directory: ./auth
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: user/app:latest