name: Análisis de métricas de calidad.

on:
  push:
    branches:
      - main

jobs:
  code-quality:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./auth

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=xml
          sed -i 's#/home/runner/work/MELI-Challenge/MELI-Challenge/auth/src#./auth/src#g' coverage.xml

        working-directory: ./auth

      #- name: Run tests with coverage
      #  run: |
      #    pytest --cov=src --cov-report=xml:./coverage.xml --cov-report=html
      #    sed -i 's/\/home\/runner\/work\/MELI-Challenge\/MELI-Challenge\/auth\/src/\.\/src/g' coverage.xml
      #  working-directory: ./auth

      - name: Project structure
        run: |
          pwd
          cat coverage.xml
          ls -R
        working-directory: ./auth

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectBaseDir: auth/
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}