name: Análisis de métricas de calidad.

on:
  workflow_call:
    secrets:
        SONAR_TOKEN:
          required: true
        SONAR_ORGANIZATION:
          required: true
        SONAR_PROJECT_KEY:
          required: true

jobs:
  code-quality:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Start Redis Docker Container
        run: |
          docker run -d --name redis_MeLi -p 6379:6379 redis/redis-stack:latest
        # Ensure Docker is running before this step
        # You can use 'docker ps' or 'docker container ls' to verify

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./auth

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=xml
          sed -i 's#/home/runner/work/MELI-Challenge/MELI-Challenge/auth/src#./auth/src#g' coverage.xml

        working-directory: ./auth

      #- name: Project structure
      #  run: |
      #    pwd
      #    cat coverage.xml
      #    ls -R
      #  working-directory: ./auth

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectBaseDir: auth/
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.python.version=${{ vars.PYTHON_VERSION }}

