name: Análisis de métricas de calidad.

on:
  workflow_call:

jobs:
  code-quality:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK ${{ vars.SONAR_JAVA_VERSION }} (SonarCloud requires JDK)
        uses: actions/setup-java@v2
        with:
          distribution: ${{ vars.SONAR_JAVA_DIST }}
          java-version: ${{ vars.SONAR_JAVA_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./auth

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=xml
        working-directory: ./auth

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Add this token in GitHub Secrets
        with:
          projectBaseDir: auth  # Set to the root directory of your project
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.python.coverage.reportPaths=coverage.xml
