name: Escaneo de seguridad de vulnerabilidades

on:
  workflow_call:
    secrets:
        DOCKER_HUB_USERNAME:
          required: true
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/meli:${{ github.sha }} .
        working-directory: ./auth

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/meli:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      